import { Presentation } from '../types/presentation';

export const demoPresentation: Presentation = {
  title: 'Демо презентация - PowerPoint Maker',
  slides: [
    {
      id: 'demo1',
      background: { type: 'color', value: '#1e40af' },
      elements: [
        {
          id: 'title1',
          type: 'text',
          content: 'Добро пожаловать в PowerPoint Maker',
          fontSize: 48,
          font: 'Arial, sans-serif',
          color: '#ffffff',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.2,
          placeholder: '',
          position: { x: 50, y: 200 },
          size: { width: 900, height: 100 },
        },
        {
          id: 'subtitle1',
          type: 'text',
          content: 'Создавайте презентации как в настоящем PowerPoint',
          fontSize: 24,
          font: 'Arial, sans-serif',
          color: '#dbeafe',
          align: 'center',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.2,
          placeholder: '',
          position: { x: 150, y: 320 },
          size: { width: 700, height: 60 },
        },
      ],
    },
    {
      id: 'demo2',
      background: { type: 'color', value: '#f8fafc' },
      elements: [
        {
          id: 'title2',
          type: 'text',
          content: 'Работа с текстом',
          fontSize: 36,
          font: 'Arial, sans-serif',
          color: '#1f2937',
          align: 'left',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.2,
          placeholder: '',
          position: { x: 100, y: 80 },
          size: { width: 800, height: 60 },
        },
        {
          id: 'feature1',
          type: 'text',
          content:
            '• Изменение размера и цвета текста\n• Выравнивание по горизонтали и вертикали\n• Жирный, курсив, подчеркивание\n• Фон текста и межстрочный интервал',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#4b5563',
          align: 'left',
          verticalAlign: 'top',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.5,
          placeholder: '',
          position: { x: 120, y: 180 },
          size: { width: 600, height: 200 },
        },
        {
          id: 'image1',
          type: 'image',
          src: 'https://via.placeholder.com/300x200/3b82f6/ffffff?text=Пример+изображения',
          position: { x: 600, y: 180 },
          size: { width: 300, height: 200 },
        },
      ],
    },
    {
      id: 'demo3',
      background: { type: 'color', value: '#fef7ed' },
      elements: [
        {
          id: 'title3',
          type: 'text',
          content: 'Работа с элементами',
          fontSize: 32,
          font: 'Arial, sans-serif',
          color: '#7c2d12',
          align: 'center',
          verticalAlign: 'top',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.2,
          placeholder: '',
          position: { x: 200, y: 50 },
          size: { width: 600, height: 50 },
        },
        {
          id: 'text3',
          type: 'text',
          content:
            '• Перетаскивайте элементы мышью\n• Изменяйте размер с помощью маркеров\n• Множественное выделение Ctrl+Click\n• Управляйте порядком элементов',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#92400e',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.6,
          placeholder: '',
          position: { x: 250, y: 120 },
          size: { width: 500, height: 150 },
        },
        {
          id: 'image2',
          type: 'image',
          src: 'https://via.placeholder.com/200x150/e11d48/ffffff?text=Элемент+1',
          position: { x: 150, y: 300 },
          size: { width: 200, height: 150 },
        },
        {
          id: 'image3',
          type: 'image',
          src: 'https://via.placeholder.com/200x150/10b981/ffffff?text=Элемент+2',
          position: { x: 400, y: 300 },
          size: { width: 200, height: 150 },
        },
        {
          id: 'image4',
          type: 'image',
          src: 'https://via.placeholder.com/200x150/f59e0b/ffffff?text=Элемент+3',
          position: { x: 650, y: 300 },
          size: { width: 200, height: 150 },
        },
      ],
    },
    {
      id: 'demo4',
      background: { type: 'color', value: '#1e293b' },
      elements: [
        {
          id: 'title4',
          type: 'text',
          content: 'Готовые шаблоны слайдов',
          fontSize: 42,
          font: 'Arial, sans-serif',
          color: '#f1f5f9',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.2,
          placeholder: '',
          position: { x: 100, y: 150 },
          size: { width: 800, height: 80 },
        },
        {
          id: 'text4',
          type: 'text',
          content:
            'Заголовочные слайды • Сравнения • Разделы\nТекст с объектами • Пустые слайды\nОбъекты с подписями • Рисунки с описанием',
          fontSize: 20,
          font: 'Arial, sans-serif',
          color: '#cbd5e1',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.8,
          placeholder: '',
          position: { x: 150, y: 280 },
          size: { width: 700, height: 120 },
        },
      ],
    },
    {
      id: 'demo5',
      background: { type: 'color', value: '#ecfdf5' },
      elements: [
        {
          id: 'title5',
          type: 'text',
          content: 'Начните творить!',
          fontSize: 38,
          font: 'Arial, sans-serif',
          color: '#065f46',
          align: 'center',
          verticalAlign: 'middle',
          bold: true,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.3,
          placeholder: '',
          position: { x: 50, y: 180 },
          size: { width: 900, height: 100 },
        },
        {
          id: 'text5',
          type: 'text',
          content:
            'Используйте панель инструментов для добавления слайдов\nРедактируйте текст двойным кликом\nСоздавайте профессиональные презентации',
          fontSize: 18,
          font: 'Arial, sans-serif',
          color: '#047857',
          align: 'center',
          verticalAlign: 'middle',
          bold: false,
          italic: false,
          underline: false,
          backgroundColor: 'transparent',
          lineHeight: 1.6,
          placeholder: '',
          position: { x: 100, y: 320 },
          size: { width: 800, height: 120 },
        },
      ],
    },
  ],
  currentSlideId: 'demo1',
  selectedSlideIds: ['demo1'],
};
